---
apiVersion: v1
kind: Namespace
metadata:
  name: crunchbot
  labels:
    name: crunchbot
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv
  namespace: crunchbot
spec:
  storageClassName: "gp2-encrypted"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: nexus-registry-credentials
  namespace: crunchbot
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - name: .dockerconfigjson
      key: eks-1/monitoring/github/github-actions-nexus-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crunchbot
  namespace: crunchbot
  labels:
    app: crunchbot
  annotations:
    log.config.scalyr.com/include: "true"
spec:
  selector:
    matchLabels:
      app: crunchbot
  template:
    metadata:
      labels:
        app: crunchbot
    spec:
      imagePullSecrets:
        - name: nexus-registry-credentials
      containers:
        - name: crunchbot
          image: docker.nexus.crint.net/crunchbot:latest
          imagePullPolicy: Always
          env:
            - name: SLACK_TOKEN
              value: "xoxb-11936109057-4272008828081-UsxRzfmjDaEOcFzCpCgIVWQy"
          ports:
            - containerPort: 8787
          volumeMounts:
            - mountPath: /crunchbot/db
              name: db
            - name: config
              readOnly: true
              mountPath: /crunchbot/config.yaml
              subPath: config.yaml
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: db-pv
      - name: config
        configMap:
          name: slack-config
---
apiVersion: v1
kind: Service
metadata:
  name: crunchbot
  namespace: crunchbot
spec:
  ports:
    - port: 8787
      protocol: TCP
      targetPort: 8787
  selector:
    app: crunchbot
  type: NodePort
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: slack-config
  namespace: crunchbot
data:
  config.yaml: |
    #use_ssl: true
    #server_host: "crunch-io.irc.slack.com"
    #server_port: 6697
    #password: "crunch-io.5ehTHZcmNtSSO4KhHgkU"
    bot_nickname: crunchbot
    message rate limit: 2.5
    log_channels: []
    other_channels: []
    inane_channel: "#inane"
    # database should be something like a MongoDB URI (mongodb://localhost)
    #  or sqlite URI (sqlite:path/filename)
    database: sqlite:/crunchbot/db/crunchbot.sqlite
    places: ["Palo Alto, CA", "Chicago", "Washington, DC", "London, England", "Durham, NC"]
    lunch_choices:
        PA: ["Pasta?", "Thaiphoon", "Pluto's", "Penninsula Creamery", "Kan Zeman"]
    feed_interval: 2 #minutes
    feeds:
        - name    : "Crunch.io on twitter"
          channel : "#Crunch-io"
          linkurl : "https://twitter.com/crunchio"
          url     : "https://twitter.com/crunchio"
    librarypaste: https://dev.crunch.io/p/
    web_base: /
    web_port: 8787
    web_host: 0.0.0.0
    #logo: /pmxbot.png
    log level: 10
    pivotal_token: e16a3a3da394d5308edc60b7a3dc68cb
    slack token: xoxb-11936109057-4272008828081-UsxRzfmjDaEOcFzCpCgIVWQy