FROM python:3.10-slim

USER root

RUN apt-get -y update; apt-get install -y bash git

RUN mkdir /crunchbot/
COPY . /crunchbot

WORKDIR /crunchbot/

#RUN pip install -r requirements.txt
RUN pip install -e .

CMD python -c "import os; f = open('config.yaml');r = f.read(); print(r.format(**os.environ))" >> live_config.yaml; /usr/local/bin/pmxbot /crunchbot/config.yaml
