#!/bin/bash -e

# force YG cheeseshop (for now)
python2.7 -c "import setuptools; setuptools.setup()" setopt -c easy_install -o index-url -s http://cheese.yougov.net
python2.7 setup.py ptr --junitxml="test results.xml"
